/* platform/sw — service worker registration and update state.
 *
 * The worker itself is generated by vite-plugin-pwa (workbox generateSW); this
 * module owns *when* it takes effect. `injectRegister: null` in vite.config.ts
 * turns off the plugin's automatic registration on purpose, because the default
 * behaviours are both wrong for a diary:
 *
 *   autoUpdate swaps the assets under a running session. The app writes to
 *   IndexedDB continuously — debounced note text, a queued dose edit — and
 *   reloading mid-write is a small but real way to lose a keystroke.
 *
 *   Silent waiting is the opposite failure: the new version sits installed and
 *   ignored for weeks, so a fix you deployed never reaches the one person using
 *   the app.
 *
 * So the update is *offered*. A banner appears, the user taps it at a moment
 * that suits them, and only then does the new worker take over. `flushAll()`
 * runs first so nothing debounced is in flight when the page goes away.
 *
 * Everything here is defensive about the API existing at all. Service workers
 * need a secure context, are absent in jsdom, and are historically the flakiest
 * corner of mobile Safari — none of which may break app startup, so every path
 * ends in "carry on without offline support".
 */

import { useEffect, useSyncExternalStore } from "react";
import { flushAll } from "../storage/store";

export type SwState = {
  /* the browser has the API and we are in a context allowed to use it */
  supported: boolean;
  /* a worker is controlling this page, i.e. assets now come from the cache
     and the next cold start works with no network */
  offlineReady: boolean;
  /* a newer version is installed and waiting for permission to take over */
  updateWaiting: boolean;
  /* set when registration itself failed; surfaced, never thrown */
  error: string | null;
};

let state: SwState = { supported: false, offlineReady: false, updateWaiting: false, error: null };
const subs = new Set<() => void>();
let reg: ServiceWorkerRegistration | null = null;
let reloading = false;

function set(patch: Partial<SwState>) {
  const next = { ...state, ...patch };
  /* useSyncExternalStore compares by identity, so avoid pointless churn */
  if (
    next.supported === state.supported &&
    next.offlineReady === state.offlineReady &&
    next.updateWaiting === state.updateWaiting &&
    next.error === state.error
  ) {
    return;
  }
  state = next;
  subs.forEach((f) => f());
}

export const getSwState = (): SwState => state;

function subscribe(fn: () => void) {
  subs.add(fn);
  return () => {
    subs.delete(fn);
  };
}

export function useSwState(): SwState {
  return useSyncExternalStore(subscribe, getSwState, getSwState);
}

export function swSupported(): boolean {
  try {
    return typeof navigator !== "undefined" && "serviceWorker" in navigator;
  } catch {
    return false;
  }
}

/* A waiting worker only means "update" if something is already controlling the
   page. On a first-ever visit the worker installs and waits with no controller,
   and calling that an update would prompt the user to reload a page they just
   opened. */
function noteWaiting() {
  const waiting = !!(reg && reg.waiting && navigator.serviceWorker.controller);
  set({ updateWaiting: waiting });
}

export function registerServiceWorker(): void {
  if (!swSupported()) return;
  set({ supported: true, offlineReady: !!navigator.serviceWorker.controller });

  const base = import.meta.env.BASE_URL || "/";
  const url = `${base}sw.js`;

  navigator.serviceWorker
    .register(url, { scope: base })
    .then((r) => {
      reg = r;
      noteWaiting();

      /* a worker found after this point is a new version */
      r.addEventListener("updatefound", () => {
        const installing = r.installing;
        if (!installing) return;
        installing.addEventListener("statechange", () => {
          if (installing.state === "installed") noteWaiting();
          /* first install completing is what makes the next cold start offline-capable */
          if (installing.state === "activated") set({ offlineReady: true });
        });
      });

      /* GitHub Pages deploys are manual and infrequent, so a check on every
         return to the app is both cheap and enough — no polling timer */
      const check = () => {
        if (document.visibilityState === "visible") void r.update().catch(() => {});
      };
      document.addEventListener("visibilitychange", check);
      window.addEventListener("online", check);
    })
    .catch((err) => {
      set({ error: err && err.message ? String(err.message) : "rekisteröinti ei onnistunut" });
    });

  navigator.serviceWorker.addEventListener("controllerchange", () => {
    set({ offlineReady: true });
    /* the new worker has taken over; reload once so the page and the assets it
       is being served match. `reloading` guards against the loop this would
       otherwise become. */
    if (reloading) {
      reloading = false;
      window.location.reload();
    }
  });
}

/* Hand control to the waiting worker, then reload. Pending debounced writes are
   flushed first: they are the only state that lives outside IndexedDB at the
   moment the page is replaced. */
export function applyUpdate(): void {
  try {
    flushAll();
  } catch {
    /* a failed flush must not block the update */
  }
  const waiting = reg && reg.waiting;
  if (!waiting) {
    window.location.reload();
    return;
  }
  reloading = true;
  waiting.postMessage({ type: "SKIP_WAITING" });
  /* controllerchange is the happy path; this is for the case where the worker
     never activates and the banner would otherwise sit there forever */
  window.setTimeout(() => {
    if (reloading) {
      reloading = false;
      window.location.reload();
    }
  }, 2500);
}

/* Test seam. The module holds process-wide state, which is fine in a browser
   and awkward in a test file that mounts the app repeatedly. */
export function __resetSwState(): void {
  state = { supported: false, offlineReady: false, updateWaiting: false, error: null };
  reg = null;
  reloading = false;
  subs.forEach((f) => f());
}

/* Used by the update banner in tests and by nothing in production. */
export function __setSwState(patch: Partial<SwState>): void {
  set(patch);
}

export function useOnlineStatus(): boolean {
  const online = useSyncExternalStore(
    (fn) => {
      window.addEventListener("online", fn);
      window.addEventListener("offline", fn);
      return () => {
        window.removeEventListener("online", fn);
        window.removeEventListener("offline", fn);
      };
    },
    () => (typeof navigator === "undefined" ? true : navigator.onLine !== false),
    () => true
  );
  useEffect(() => {
    /* nothing to do; the subscription is the whole mechanism */
  }, []);
  return online;
}
